<?php

function cipher_menu() {
    $items['caesar'] = array(
        'title' => 'Caesar Cipher', //Content Title
        'page callback' => 'drupal_get_form', //Callback function for view - uses built in drupal function to return form as callback.
        'page arguments' => array('caesar_form'),
        'access callback' => TRUE, //Give all users access
        'type' => MENU_NORMAL_ITEM, //Menu Item Type
    );
    $items['caesar_success_page'] = array(
        'title' => 'You Got This!',
        'page callback' => 'caesar_success',
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
    );
    return $items;
}

//Function to Build Out the Form - Accessed via the Callback Function on the 'caesar' route
function caesar_form() {
    $form['shift_value'] = array(
        '#title' => 'Shift Value',
        '#type' => 'textfield',
        '#attributes' => array('placeholder' => t('Enter Number Between 1 and 25')),
        '#required' => TRUE,
        '#element_validate' => array('element_validate_integer_positive', 'element_validate_range'),
    );

    $form['shift_direction'] = array(
        '#title' => 'Shift Direction',
        '#type' => 'textfield',
        '#attributes' => array('placeholder' => t('Enter Right or Left Shift Direction')),
        '#required' => TRUE,
        '#element_validate' => array('element_validate_direction'),
    );

    $form['phrase'] = array(
        '#title' => 'Phrase',
        '#type' => 'textarea',
        '#attributes' => array('placeholder' => t('Enter Your Phrase (Max 255 Characters)')),
        '#required' => TRUE,
        '#rows' => 3,
        '#resizable' => FALSE,
        '#maxlength' => 255,
        '#element_validate' => array('element_validate_sanitize'),
    );

    $form['submit'] = array(
        '#type' => 'submit',
        '#value' => 'Submit',
    );

    return $form;
}

function element_validate_range($element) {
    if ($element['#value'] > 25 || $element['#value'] < 1 ) {
        form_error($element, t('Please Enter a Number Between 1 and 25.'));
    }
}

function element_validate_direction($element) {

    $valid_directions = array('right', 'left');

    $direction = strtolower($element['#value']);
    $direction = trim($direction);

    if (!in_array($direction, $valid_directions)) {
        form_error($element, t('Please Enter Right or Left.'));
    }
}

function element_validate_sanitize($element) {

    $valid_punctuation = array(".", "!", "?", ",", " ");
    $alphabet = array('a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z');

    $filter_punctuation = $element['#value'];
    $filter_punctuation = str_replace($alphabet, "", $filter_punctuation);
    $filter_punctuation = str_split($filter_punctuation);

    foreach($filter_punctuation as $punctuation) {
        if (!in_array($punctuation, $valid_punctuation)) {
            form_error($element, t('Valid Punctuation Only: Periods, Exclamation, Question, Comma or Space'));
        }
    }
}

// Form Submit Function for caeser form - process login and redirects to success page on button click
function caesar_form_submit($form, &$form_state) {

//validation alphabet in lowercase as asked in the assignment (uppercase looks nicer - change after grading)
    $alphabet = array('a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z');

    $shift_value = $form_state['values']['shift_value'];
    $shift_value = filter_var($shift_value, FILTER_SANITIZE_STRING);
    $shift_direction = $form_state['values']['shift_direction'];
    $shift_direction = filter_var($shift_direction, FILTER_SANITIZE_STRING);
    $original_phrase = $form_state['values']['phrase'];
    $original_phrase = filter_var($original_phrase, FILTER_SANITIZE_STRING);

//simplify direction
    $direction = strtolower($shift_direction);
    $direction = trim($direction);

//create the letters array from the original phrase
    $letters = strtolower($original_phrase);
    $letters = str_split($letters);

//create holding array for loop values
    $caesar_array = array();

// for each item in the letters single letter array
    foreach ($letters as $letter) {
        $key = array_search($letter, $alphabet);

        if ($direction == 'right') {
            $cipher_key = $key + $shift_value;
        } elseif($direction == 'left') {
            $cipher_key = $key - $shift_value;
        }
        // if the item in the letters single letter array is an empty string, push the empty string to the array.
        if (!in_array($letter, $alphabet)) {
            array_push($caesar_array, $letter);
        } else {
            if ($cipher_key < 0) {
                $cipher_key = $cipher_key + 26;
            } elseif ($cipher_key > 26) {
                $cipher_key = $cipher_key - 26;
            } else {
                $cipher_key = $cipher_key;
            }
            array_push($caesar_array, $alphabet[$cipher_key]);
        }
    }

    $caesar_phrase = implode('', $caesar_array);

    $_SESSION['original_phrase'] = $original_phrase;
    $_SESSION['caesar_phrase'] = $caesar_phrase;

    $form_state['redirect'] = 'caesar_success_page';
}

// Success View for Caesar Form
function caesar_success() {
    $original_phrase = $_SESSION['original_phrase'];
    $caesar_phrase = $_SESSION['caesar_phrase'];
    return 'Keep it secret, keep it safe! Here is your translated phrase \'' . $caesar_phrase . '\' from the original version of \'' . $original_phrase . '.\'';
}
